### ISSUE TITLE
Hey sry for using this tool, can you contact me?

### ISSUE THREAD

**Issue by shanks24** [TaylorMouse/MaxScripts#1]
I always work with 3ds max for warcraft 3 
I like to help you, by creating your tool. I am really good with models

Is there any way, that you can contact me at Discord? my name is Dennis
#2024

**Comment by TaylorMouse** [comment]
Hey D, I think we covered this ;) so closing the isse

**Comment by phamtheson01** [comment]
could you add me too? mine is Cyan#0361
