### ISSUE TITLE
Excuse me, does it support new model and bone export? When I use it to export self built models and bones, model deformation occurs

### ISSUE THREAD

**Issue by lcfkbs** [TaylorMouse/MaxScripts#10]

**Comment by lcfkbs** [comment]
After importing 'Warcraft 3 reconstructed' model, exporting 'mdx' is normal，but When I use the export function to export the model of "skyrim", the model deformation occurs when I import it into the 'Warcraft 3 Reforget map editor'. 
![001](https://user-images.githubusercontent.com/67427525/117535086-afd2b680-b026-11eb-9a52-3ded27c07126.png)

**Comment by lcfkbs** [comment]
Supplement : Warcraft 3 Reforget map editor

**Comment by lcfkbs** [comment]
When a user-defined model has only one bone weight, it is normal to import it into the map editor. If there is more than one bone weight, the model will be pulled and deformed

**Comment by lcfkbs** [comment]
![_E V{@`V7)79EHNOY WWU{F](https://user-images.githubusercontent.com/67427525/117546152-a0ba2b80-b05b-11eb-871f-e73f79ab9efa.png)
After importing the "Warcraft 3" model, delete the skin and leave the bones, and then import the skin with skin data in "NIF" format. Although it is much more normal, it still has defects

Infernal

**Comment by lcfkbs** [comment]
Also, thank you very much for your work that has made many ideas possible

**Comment by lcfkbs** [comment]
Although there will be some defects in exporting "Warcraft 3" model to NIF format and importing it into 'Max', the bones and models of "Warcraft 3" will be much more normal than those of 'skyrim'. When 'skyrim' model has only one bone weight, the imported map editor model will not pull and deform. If there is more than one bone weight, the model will pull and deform. These are the problems that I have encountered when using the export function. I don't know if my usage is wrong

**Comment by TaylorMouse** [comment]
I don't think your using is wrong, I think my lack of better knowledge of how to read from the max scene prevents me from doing these things correcly... in the meantime I did do an update ( if I remember correctly) maybe check again ?
