### ISSUE TITLE
Tested with 3D Max 2022?

### ISSUE THREAD

**Issue by ta-vroom** [TaylorMouse/MaxScripts#11]
I'm running the above version (didn't see a means to downgrade) and running into a few errors. I saw that errors were popping up with previous versions and wanted to check it wasn't an issue with my install.

**Comment by TaylorMouse** [comment]
Can you specify the issues?

**Comment by ta-vroom** [comment]
```
--	------------------------------------------------------
--	[stack level: 0]
--	In btnImport.pressed(); filename: C:\Program Files\Autodesk\3ds Max 2022\scripts\startup\GriffonStudios_Warcraft_3_Reforged_Tools\GriffonStudios_Warcraft_3_Reforged_Macros.ms; position: 2221; line: 57
--	member of: Rollout:ImportWindow
--		Locals:
--			Warcraft3_Reforged: undefined
--			file: "C:\Users\*\Desktop\war3.w3mod\units\demon\chaosgrunt\chaosgrunt.mdx"
--		Externals:
--			ImportWindow: Rollout:ImportWindow
--			owner: Rollout:ImportWindow
--			txtSelectedFile: RolloutControl:txtSelectedFile in rollout:ImportWindow : EditTextControl:txtSelectedFile
--	------------------------------------------------------
--	[stack level: 1]
--	called from top-level
```

Sorry for the late reply, but I just installed 3ds max on Windows 11. 

Is it looking for the Reforged install? I haven't installed it yet, but can do.

Edit: Installing Reforged didn't fix the issue.

**Comment by ta-vroom** [comment]
I think my error's related to changes in GriffonStudios_Warcraft_3_Reforged_Main.ms in this commit:   3e786aa9bd5ded61774a92fcb48d6e29e016f384 

I tried using an older file and I wasn't getting that import error.

**Comment by TaylorMouse** [comment]
Oh, you are using the reforged stuff, I haven't worked on this for a long time and the export is not working at all ...

**Comment by TaylorMouse** [comment]
After the mdx 800 stuff works, I'll be looking into this again afterwards, it could take a while though
