### ISSUE TITLE
does this support old version of warcraft 3?

### ISSUE THREAD

**Issue by IceWolf0110** [TaylorMouse/MaxScripts#13]
1.31 and below...

**Comment by TaylorMouse** [comment]
If you mean the version 800 mdx files, from the original game ( not reforged ) then YES.
All my test were done on Warcraft III v 1.0.1 and Warcraft III Frozen Throne 1.5.0

Hope this answers your question.
If not, please provide me a model that I can test

T.

**Comment by IceWolf0110** [comment]
here's a test model ripped from Dota 2. Cant be exported.
[base_recover.zip](https://github.com/TaylorMouse/MaxScripts/files/6959146/base_recover.zip)
