### ISSUE TITLE
UV mapping is incorrectly set on certain models. Starcraft 2

### ISSUE THREAD

**Issue by Onixiya** [TaylorMouse/MaxScripts#16]
The position and scale of it is incorrect on some models such as banshee.m3 Most models i've thrown through it have the UV map 100% correct (least from what i noticed). Its a simple fix to do manually as you just need to play with the scale and its position but still a bit annoying that its happening to begin with and thought i would make a issue to see if it could be fixed. 3dsmax 2016 as well if that helps with anything
![image](https://user-images.githubusercontent.com/29950414/166485318-529cd03d-f2ee-43be-aec9-7d0e6d96ca00.png)

**Comment by GaaRa0** [comment]
I have same issue UV with GriffonStudios_Starcraft_HotS_M3_Import_v3.5.ms ,
Other Import have no problem at all ,animation bone not have any problem ,UV map is broken

**Comment by TaylorMouse** [comment]
It is not broken you just have to scale it correctly, but I have searched so long for that to work, I gave up on it.
