### ISSUE TITLE
Script errors

### ISSUE THREAD

**Issue by Darkloke** [TaylorMouse/MaxScripts#17]
Greetings. Dunno what the case, but the scripts dont work for me. Tested both in 3Ds max 2016 and 2020 - the same errors at launch.

And also i have a question about m2 models (creatures) importing from WoW. In script settings there is a path to DBFiles Client, but which one to set here? From what i know *.dbc files used until Battle for Azeroth, from which one they started to use *.db2 files. GriffonStudios folder have animationdata files in both formats, so i suppose script itself chooses what to use? I tried for example import creature/warden/warden.m2 from Battle of Azeroth pointing in script settings path to GriffonStudios files, but got an error at import.

19.06.22 Small update - it seems database format changed from *.dbc to *.db2 not in legion-bfa transition, but in draenor-legion.

![Screenshot_1](https://user-images.githubusercontent.com/4979638/173420885-65e54816-571f-4957-b498-6a19a687ae44.png)
![Screenshot_3](https://user-images.githubusercontent.com/4979638/173420888-8d64fab5-6538-44ee-af24-1624dc75a0f7.png)
![Screenshot_5](https://user-images.githubusercontent.com/4979638/173420891-d1e750e9-6cbd-4801-8fbd-c201052ed04d.png)
![Screenshot_6](https://user-images.githubusercontent.com/4979638/173420892-90f77ca5-b909-42ff-bf03-20289e772556.png)
![Screenshot_9](https://user-images.githubusercontent.com/4979638/173420893-39378582-754d-40f0-8286-38b0bbb2d5c7.png)
![Screenshot_10](https://user-images.githubusercontent.com/4979638/173420894-befe80f0-68f8-4793-80a9-7da5c4c471c9.png)
![Screenshot_11](https://user-images.githubusercontent.com/4979638/173420896-1a6f3f94-2dc6-44ef-b1a5-0ad687944c65.png)
![Screenshot_12](https://user-images.githubusercontent.com/4979638/173420898-35242329-cc47-4008-8928-93fc0ec82981.png)
![Screenshot_2](https://user-images.githubusercontent.com/4979638/173426987-962b2574-4338-4676-ab94-9daddf156116.png)
.

**Comment by TaylorMouse** [comment]
since I'm not the author of that script, I just changed it for my benefit... I can' really help you
