### ISSUE TITLE
Import incorrect position and scale of SC2 model UVmap

### ISSUE THREAD

**Issue by GaaRa0** [TaylorMouse/MaxScripts#18]
![pic](https://user-images.githubusercontent.com/110744524/185798653-c4aad0a0-c556-40c7-bdf2-c5016cc3b013.png)
GriffonStudios_Starcraft_HotS_M3_Import.ms
Incorrect UVMap position and scale of SC2 model 
UVMap size should be fill the center ,UVMap it outside the UVMap texture and wrong scale not right scale 
,Animation Bone not have any bug and work perfectly ,Import without SC2ArtTool 
Is this script [GriffonStudios_Starcraft_HotS_M3_Import.ms] work with 3DSMax2021?
Should I install SC2ArtTool2016 to fix the bug? It not work with 3DSMax2021

GriffonStudios_WoW_M2_Import.ms
script can't import some model geoset correctly like Dreadlordshadowland Gnoll2 Centaur2 (mostly creature base)
and model with .anim file(wow animation) has no animation after import
some of wow dragonfilght model have bug, 
arm elbow or front leg knee broken while converting to warcraft3 animation in 3ds max is normal ,look like warcraft3 not read that bone or attachment or something (mammoth2 front leg knee for example)

Request GriffonStudios_WoW_M2_Import.ms [WoW_M2Character_Import.ms] for import character model only
If you want to update M2 Import script for character model need to import bone and attachment from .skel file 
https://wowdev.wiki/M2
https://wowdev.wiki/M2/.skel
Character base and night elf archer use .skel file

PS. Love your script

**Comment by TaylorMouse** [comment]
For the SC2 model uv incorrect loading, I searched so long that I gave up, I just have like totally no clue how to import it correctly. I change it manually.

M2 import is a script I modified to mke my life easier, is not mine so I don't maintain it.

**Comment by GaaRa0** [comment]
Thank

> change it manually

Can you tell me how to do that? ,You already have manually UV setting
