### ISSUE TITLE
UV Mapping on m3 Models (HotS) is missplaced and wrongly scaled

### ISSUE THREAD

**Issue by DMI-1407** [TaylorMouse/MaxScripts#20]
the UV Maps on m3 models doesn't fit, i remember it working back in the days... what was the last HotS version where it worked with?
Also i remember the models more modular, like that you could easily select parts (attachments? e.g. armor) which isn't possible anymore, but maybe i just checked on the wrong models.

**Comment by TaylorMouse** [comment]
It never worked 100% there are always models that have the UV Map misplaced, you need to correct them manually using the uv unwrap modifier.
