### ISSUE TITLE
Does not work properly with 3dsMAX 2016

### ISSUE THREAD

**Issue by startmuscle0731** [TaylorMouse/MaxScripts#6]
Thank you for the wonderful plugin. I tried to use this plugin to get Diablo III models and anime.

I have placed "GriffonStudios_Startup.ms" and "GriffonStudios" in C: \ Program Files \ Autodesk \ 3ds Max 2016 \ scripts \ Startup, but when I launch it I get a load dialog and when I close dialog it I get a lot of error messages.

After clearing the error message, I can operate it, but when I try to import the Diablo III model, I get an error.
"--Unknown property:" ParID "in (D3Bone id: 1 name:" Root "TheBone: undefined)"

It doesn't seem to be working properly at startup. Is there any way to fix it?

-----------
*Error Message

Maximum Nested Error Dialog Depth Reached
Attempt to display more that maximum number of simultaneous error message dialogs occured.
See error log file for additional error messages

**Comment by startmuscle0731** [comment]
After further verification, if you select the file in the dialog as it is, an error will occur. However, when I loaded the Diablo III script with Run Script (nothing was displayed), after that, selecting a file in the dialog did not cause an error, and I was able to import the model and animation normally. After all, there seems to be a problem with the startup.

**Comment by TaylorMouse** [comment]
Yes, I have the same issue, it is indeed not the code, as you, I rerun the script and it worked, so I'm looking into the startup, it may be that the appropriate script (s) are not loaded at runtime :/
I tested this with 2020 and it seems to working. Probably another Max issue (as there are many )

**Comment by TaylorMouse** [comment]
Ok, fixed
