### ISSUE TITLE
Wrong name on tmp ini config for reforged assetFolder

### ISSUE THREAD

**Issue by Jaccouille** [TaylorMouse/MaxScripts#9]
I followed the instruction on the readme.md & pdf earlier this day.

Noticed materials didn't have textures file on reforged mdx file import.

Tried to debug : 
When setting the asset folder using the setting dialog, it saves the assetFolder path in a ini file named [wc3ref.config](https://github.com/TaylorMouse/MaxScripts/blob/8594049ed71889171c67e6c2c9b889018eec5634/GriffonStudios_Warcraft_3_Reforged_Tools/GriffonStudios_Warcraft_3_Reforged_Macros.ms#L109)

When importing a reforged model, it looks for a ini file named [griffonstudios.config](https://github.com/TaylorMouse/MaxScripts/blob/8594049ed71889171c67e6c2c9b889018eec5634/GriffonStudios_Warcraft_3_Reforged_Tools/GriffonStudios_Warcraft_3_Reforged_Main.ms#L3234)

Warcraft3_AssetFolder global end up behind an empty string and I get the warning displayed.

Fixed the issue by replacing "griffonstudios.config" by "wc3ref.config".
Didn't make a pull request because I don't know which name you intend to use for this file.

**Comment by TaylorMouse** [comment]
thank you, yes, I use griffonstudios.config in everything normally but ppl asked me to split this up so I went to wc3ref.config... looks like I forgot a part to change
